package eubr.atmosphere.tma.planning

dialect "java"

import eubr.atmosphere.tma.planning.AdaptationManager
import eubr.atmosphere.tma.data.Action
import eubr.atmosphere.tma.data.Configuration
import eubr.atmosphere.tma.utils.TrustworthinessScore
import eubr.atmosphere.tma.utils.ResourceConsumptionScore
import java.util.List
import java.util.ArrayList

declare TrustworthinessScore
      @role(event)
      @expires(1s)
      //@timestamp (eventDestinationTimestamp)
 end

rule "Starling Actuation Rule"
    when
        $score: TrustworthinessScore ( securityScore.score > 0.1800 )
    then
        System.out.println("Starling Actuation");
        List<Action> actionList = new ArrayList();
        Action action = new Action(80001, "createCase", $score.getSecurityScore().getResourceId(), 80001);
        actionList.add(action);
        AdaptationManager.performAdaptation( actionList, AdaptationManager.obtainMetricData($score.getSecurityScore()) );
end


rule "Privacy Score Validation - Increase PRIVAAS Anonymization"
    when
        $score: TrustworthinessScore ( privacyScore.score < privacyScore.threshold )
    then
        List<Action> actionList = new ArrayList();
        Action action = new Action(35001, "update", 8, 35001);
        AdaptationManager.performAdaptation( actionList, AdaptationManager.obtainMetricData($score.getPrivacyScore()) );
end

rule "Privacy Score Validation - Not Increase PRIVAAS Anonymization"
    when
        $score: TrustworthinessScore ( privacyScore.score >= privacyScore.threshold,
                                       privacyScore.score != 0.0,
                                       privacyScore.threshold != 0.0)
    then
        List<Action> actionList = new ArrayList();
        Action action = new Action(35002, "none", 8, 35001);
        AdaptationManager.performAdaptation( actionList, AdaptationManager.obtainMetricData($score.getPrivacyScore()) );
end
