package eubr.atmosphere.tma.planning
 
dialect "mvel"

import eubr.atmosphere.tma.planning.AdaptationManager
import eubr.atmosphere.tma.data.Action
import eubr.atmosphere.tma.data.Configuration
import eubr.atmosphere.tma.utils.SecurityScore

declare SecurityScore
      @role(event)
      @expires(1s)
      //@timestamp (eventDestinationTimestamp)
 end

rule "Starling Actuation Rule"
    when
        $score: SecurityScore ( score > 0.1400 )
    then
	    System.out.println("Starling Actuation");
        Action action = new Action(80001, "createCase", $score.resourceId, 80001);
        action.addConfiguration(new Configuration(80001, "incidentId", "38"));
        action.addConfiguration(new Configuration(80002, "incidentSource", "CloudEA"));
        action.addConfiguration(new Configuration(80003, "subject", "Non-complient policy discovered"));
        action.addConfiguration(new Configuration(80004, "summary",
            "Non-complient policy discovered by Boris Giterman. Please check your McAffee policy distribution"));
        action.addConfiguration(new Configuration(80005, "is_public", "true"));
        action.addConfiguration(new Configuration(80006, "caseType", "INCIDENT"));
        action.addConfiguration(new Configuration(80007, "aggregatedDomain", "Starling"));
        AdaptationManager.performAdaptation( action, AdaptationManager.obtainMetricData($score) );
end