package eubr.atmosphere.tma.planning
 
dialect "mvel"

import eubr.atmosphere.tma.planning.AdaptationManager
import eubr.atmosphere.tma.data.Action
import eubr.atmosphere.tma.data.Configuration
import eubr.atmosphere.tma.utils.SecurityScore

declare SecurityScore
      @role(event)
      @expires(1s)
      //@timestamp (eventDestinationTimestamp)
 end

rule "Starling Actuation Rule"
    when
        $score: SecurityScore ( score > 0.1400 )
    then
	    System.out.println("Starling Actuation");
	    // I am not sure if this resource Id is correct
        Action action = new Action(80001, "createCase", 80101, 80001);
        action.addConfiguration(new Configuration(80001, "incidentId", "value"));
        action.addConfiguration(new Configuration(80002, "incidentSource", "value"));
        action.addConfiguration(new Configuration(80003, "subject", "value"));
        action.addConfiguration(new Configuration(80004, "summary", "value"));
        action.addConfiguration(new Configuration(80005, "is_public", "value"));
        action.addConfiguration(new Configuration(80006, "caseType", "value"));
        action.addConfiguration(new Configuration(80007, "aggregatedDomain", "value"));
        AdaptationManager.performAdaptation( action, AdaptationManager.obtainMetricData($score) );
end