package eubr.atmosphere.tma.planning
 
dialect "mvel"

import eubr.atmosphere.tma.planning.AdaptationManager
import eubr.atmosphere.tma.data.Action
import eubr.atmosphere.tma.data.Configuration
import eubr.atmosphere.tma.utils.TrustworthinessScore

declare TrustworthinessScore
      @role(event)
      @expires(1s)
      //@timestamp (eventDestinationTimestamp)
 end

rule "Score validation - TeaStore Scale up"
    when
        $score: TrustworthinessScore ( resourceConsumptionScore.score > 0.0800, podCount < 3 )
    then
        Action action = new Action(1, "scale", 9, 5);
        action.addConfiguration(new Configuration(1, "metadata.namespace", "default"));
        action.addConfiguration(new Configuration(2, "metadata.name", "teastore-webui"));
        action.addConfiguration(new Configuration(3, "spec.replicas", "3"));
        AdaptationManager.performAdaptation( action );
end

rule "Score validation - Wildfly Scale down"
    when
        $score: TrustworthinessScore ( resourceConsumptionScore.score < 0.0240, podCount > 1 )
    then
        Action action = new Action(1, "scale", 9, 5);
        action.addConfiguration(new Configuration(1, "metadata.namespace", "default"));
        action.addConfiguration(new Configuration(2, "metadata.name", "teastore-webui"));
        action.addConfiguration(new Configuration(3, "spec.replicas", "1"));
        AdaptationManager.performAdaptation( action );
end
