package eubr.atmosphere.tma.planning
 
dialect "mvel"

import org.apache.kafka.clients.consumer.ConsumerRecord
import eubr.atmosphere.tma.planning.AdaptationManager
import eubr.atmosphere.tma.planning.Action

/*import org.drools.examples.services.Post
import org.drools.examples.probes.ReadingEvent

import java.util.ArrayList

declare ReadingEvent
      @role(event)
      //@expires(1s)
      //@timestamp (eventDestinationTimestamp)
 end*/
 
rule "Score validation"
    when
        $number: Number ( )
    then
        System.out.println( "The current score is: " + $number.toString());
end

rule "Add dummy action"
    when
        $c : ConsumerRecord (  )
    then
        System.out.println( "Validating if the rules file works :) " + $c);
        System.out.println( "Value is " + $c.value);

        Action action = new Action("Test Action drools", 45);
        AdaptationManager.performAdaptation( action );
end

rule "Score validation"
    when
        $score: Score ( score > 0.4 )
    then
        System.out.println( "The current score is high: " + $score.toString());
end

/*rule "[Probes] Request Rest"

    when
        $p : Post(id == 13)
    then
        System.out.println( "[Probes] I am " + $p.id + " / Title: " + $p.title );
        Actuator.adapt($p.id);
end

rule "[Probes] Post added"

    when
        $p : Post((id %2) == 0)
    then
        System.out.println( "[Probes] Id: " + $p.id + " / Title: " + $p.title );
end

rule "[Probes] Change Max after 3 occurrences"

	when
		Number( avg : doubleValue > 25.0 ) from accumulate(
			ReadingEvent( $reading_value : value ) over window:length( 3 ), 
			average ( $reading_value ) )
		$p : Producer(  )
	then
		System.out.println( "[Probes] Changing behavior (max)" );
		System.out.println( avg );
		modify ( $p ) { setMax (25 - $p.min) }
end*/
